
proxy:
  - servername: 
     - "exemplo.com"
     - "www.exemplo.com"
     - "200.123.123.123"
    tls: false
    cert: "/etc/letsencrypt/live/exemplo.com/fullchain.pem"
    certkey: "/etc/letsencrypt/live/exemplo.com/privkey.pem"
    locations: 
     - path: "/"
       endpoint: "http://primeiro:8080"
     - path: "/testepath"
       endpoint: "http://segundo:80"
  - servername: 
     - "outroexemplo.com"
     - "www.outroexemplo.com"
    tls: false
    cert: "/etc/letsencrypt/live/outroexemplo.com/fullchain.pem"
    certkey: "/etc/letsencrypt/live/outroexemplo.com/privkey.pem"
    locations: 
     - path: "/"
       endpoint: "http://container-name:80"
     - path: "/relatorio"
       endpoint: "http://container-relatorios:80"